# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\login_register.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginRegister(object):
    def setupUi(self, LoginRegister):
        LoginRegister.setObjectName("LoginRegister")
        LoginRegister.resize(799, 474)
        self.centralwidget = QtWidgets.QWidget(LoginRegister)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color:rgb(207, 207, 207);\n"
"color:black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color:white;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.frame_login_register = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_login_register.sizePolicy().hasHeightForWidth())
        self.frame_login_register.setSizePolicy(sizePolicy)
        self.frame_login_register.setStyleSheet("QFrame#frame_login_register{\n"
"background:transparent;\n"
"border:3px inset gray;\n"
"border-radius:3px;\n"
"}")
        self.frame_login_register.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login_register.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login_register.setObjectName("frame_login_register")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_login_register)
        self.verticalLayout_6.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_login_register = QtWidgets.QLabel(self.frame_login_register)
        self.label_login_register.setStyleSheet("font-weight:bold;\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.label_login_register.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login_register.setObjectName("label_login_register")
        self.verticalLayout_6.addWidget(self.label_login_register)
        self.label_login_register_detail = QtWidgets.QLabel(self.frame_login_register)
        self.label_login_register_detail.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_login_register_detail.setWordWrap(True)
        self.label_login_register_detail.setObjectName("label_login_register_detail")
        self.verticalLayout_6.addWidget(self.label_login_register_detail)
        self.line_3 = QtWidgets.QFrame(self.frame_login_register)
        self.line_3.setStyleSheet("background-color:rgb(195, 195, 195)")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_6.addWidget(self.line_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_6.addItem(spacerItem4)
        self.label_3 = QtWidgets.QLabel(self.frame_login_register)
        self.label_3.setStyleSheet("color: black;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.lineEdit_username = QtWidgets.QLineEdit(self.frame_login_register)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_username.setStyleSheet("")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout_6.addWidget(self.lineEdit_username)
        self.label_6 = QtWidgets.QLabel(self.frame_login_register)
        self.label_6.setStyleSheet("color: black;\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.lineEdit_password = QtWidgets.QLineEdit(self.frame_login_register)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_6.addWidget(self.lineEdit_password)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_6.addItem(spacerItem5)
        self.frame_10 = QtWidgets.QFrame(self.frame_login_register)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.btn_login_register = QtWidgets.QPushButton(self.frame_10)
        self.btn_login_register.setMinimumSize(QtCore.QSize(150, 30))
        self.btn_login_register.setStyleSheet("background-color:rgb(207, 207, 207);\n"
"color:black;\n"
"font: 11pt \"MS Shell Dlg 2\";\n"
"border:2px inset gray;\n"
"border-radius:3px;")
        self.btn_login_register.setObjectName("btn_login_register")
        self.horizontalLayout_3.addWidget(self.btn_login_register)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_6.addWidget(self.frame_10)
        self.btn_register_login = QtWidgets.QPushButton(self.frame_login_register)
        self.btn_register_login.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_register_login.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_register_login.setStyleSheet("background-color:transparent;\n"
"padding:5px;\n"
"border-radius:10px;\n"
"color:rgb(0, 0, 127);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"text-decoration:underline;")
        self.btn_register_login.setObjectName("btn_register_login")
        self.verticalLayout_6.addWidget(self.btn_register_login)
        self.verticalLayout_2.addWidget(self.frame_login_register)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.horizontalLayout.addWidget(self.frame_3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout.addWidget(self.frame_2)
        LoginRegister.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginRegister)
        QtCore.QMetaObject.connectSlotsByName(LoginRegister)

    def retranslateUi(self, LoginRegister):
        _translate = QtCore.QCoreApplication.translate
        LoginRegister.setWindowTitle(_translate("LoginRegister", "Pacemaker: Device Controller Monitor"))
        self.label.setText(_translate("LoginRegister", "<html><head/><body><p><span style=\" font-size:22pt; color:#000000;\">Device Controller Monitor</span></p></body></html>"))
        self.label_login_register.setText(_translate("LoginRegister", "LOGIN"))
        self.label_login_register_detail.setText(_translate("LoginRegister", "Please enter your credentials for login"))
        self.label_3.setText(_translate("LoginRegister", "Username"))
        self.label_6.setText(_translate("LoginRegister", "Password"))
        self.btn_login_register.setText(_translate("LoginRegister", "Login"))
        self.btn_register_login.setText(_translate("LoginRegister", "Already Have an account? Sign Up"))
